# IP Max:
# IP Andy:
# IP Henrik: 192.168.178.121


server:
  port: 8880
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.178.121:8761/eureka 

# defaultZone: http://insertOwnIP:8761/eureka 


spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: article
        uri: http://192.168.178.121:8180/
# uri: http://insertOwnIP:8180/
        predicates:
        - Path=/article/**
      - id: order
        uri: http://192.168.178.121:8280/
# uri: http://insertOwnIP:8180/
        predicates:
        - Path=/order/**
      - id: customer
        uri: http://192.168.178.121:8380/
# uri: http://insertOwnIP:8180/
        predicates:
        - Path=/customer/**